### PR TITLE
Add Account Class

### PR DESCRIPTION
**Pull request by Johnsavadkuhi**
#82

### CODE REVIEW

**Comment by notatestuser** [comment]
This is a more significant structure change, we will reserve this for a next big release

**Comment by notatestuser** [comment]
And thanks!

**Comment by notatestuser** [comment]
Just one question about this - It seems that `getBalance` be part of the `Account` class?

**Comment by Johnsavadkuhi** [comment]
@notatestuser  i think getBalance should be in client class. it is only a recommend

**Pull request closed without merging**
